#sdk: "/home/nivedita/.rvm/gems/ruby-1.9.2-p290/gems/rhodes-3.3.4"
sdkversion: 3.3.4
name: survey-mobile
version: 1.0
vendor: rhomobile
build: debug
bbver: 4.6
applog: rholog.txt
iphone:
  configuration: Release
  sdk: iphonesimulator5.0
  provisionprofile:
  codesignidentity:
  entitlements:
  BundleIdentifier: com.rhomobile.survey-mobile
  BundleURLScheme: survey-mobile
wp:
  productid: 'daa54490-c99a-012f-6b93-704da2661777'
symbian:
  uid: '0xe4d1a4f7'
android:
  version: 2.3.3

extensions: ["json", "another-extension"]
