var Palette = {
  BLACK : "#000",
  GRAY_XDARK : "#222",
  GRAY_DARK : "#444",
  GRAY : "#666",
  GRAY_MLIGHT : "#999",
  GRAY_LIGHT : "#CCC",
  GRAY_XLIGHT : "#EEE",
  GRAY_XXLIGHT : "#F7F7F7",
  WHITE : "#FFF",

  HIGHLIGHT : "#FFE",
  YELLOW : "#FF0",

  DANGER : "#C00",
  DANGER_LIGHT : "#FCC",

  GREEN : '#A4C739',
  RED : '#DA0000',

  PRIMARY_COLOR: "#101C26",
  PRIMARY_COLOR_LIGHT: "#4D5A6B",

  SECONDARY_COLOR: "#DAB88B",
  SECONDARY_COLOR_DARK: "#CD8322",
  SECONDARY_COLOR_LIGHT: "#FAE19E"
};

module.exports = Palette;
